### ISSUE TITLE
Images in description 

### ISSUE THREAD

**Issue by klorydryk** [tobihille/SeniorLauncher#7]
Would it be possible to add images to the description? For a launcher design oriented, it would be useful for understand the interest to use it for a senior.

**Comment by tobihille** [comment]
I will try that. It's my first Android app and therefore the first I added to F-Droid so I'm unfamiliar with the process. Hopefully I will find time when it's weekend.

**Comment by tobihille** [comment]
As a first step I created sample images, the are here: https://github.com/tobihille/SeniorLauncher/tree/master/Screenshots

**Comment by tobihille** [comment]
I *think* I figured out how to add images. I created a merge request on fdroid: https://gitlab.com/fdroid/fdroiddata/merge_requests/4256
Let's see what happens :-)
Also I added a link to the releases: https://github.com/tobihille/SeniorLauncher/releases so users can see what's new. Additionally all contributors should get their credits even in fdroid because I mention them when I create a new release (a tag in git).
I'm excited if everything works as planned.
I will close this issue but will have a look to the linked merge request. If nothing has happened within a week I will most certainly open it again (when I added the app it took a few days until everything was good).
